language: php

php:
  - '7.0'
  - '7.1'
  - nightly

cache:
  directories:
    - /home/travis/.composer
    - vendor/
    - htdocs/content/themes/themosis-theme/vendor
    - node_modules/
    - htdocs/content/themes/themosis-theme/node_modules

before_script:
  - cd "$TRAVIS_BUILD_DIR/" && composer install --no-suggest --no-progress -ao
  - cd "$TRAVIS_BUILD_DIR/theme" && composer install --no-suggest --no-progress -ao

script:
  - cd "$TRAVIS_BUILD_DIR" && vendor/bin/phpunit
  - cd "$TRAVIS_BUILD_DIR/theme" && vendor/bin/phpcs --colors
