version: "2.2"

# Create a network
networks:
  gumbo-site:
    driver: bridge

# Create a vitual volume for the SQL storage
volumes:
  mysql-data:
  cache-storage:

services:
  # Webserver, nginx
  web:
    build:
      context: ./
      dockerfile: ./docker/web.dockerfile
    hostname: gumbo.example
    networks:
      - gumbo-site
    ports:
      - "127.0.0.1:8337:80"
      - "127.10.0.1:80:80"
    environment:
      APP_MODE: 'test'
    volumes:
      - .:/var/www:ro
    depends_on:
      - php

  # PHP 7.1 FPM
  php:
    image: roelofr/php:fpm
    hostname: php.gumbo.example
    networks:
      - gumbo-site
    environment:
      APP_MODE: 'test'
    volumes:
      - .:/var/www
    depends_on:
      mysql:
        condition: service_healthy

  # MariaDb, cause f*ck Oracle
  mysql:
    image: mariadb
    hostname: mysql.gumbo.example
    networks:
      - gumbo-site
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "127.10.0.1:3306:3306"
    healthcheck:
      test:
        - "CMD-SHELL"
        - "mysql --user=root --password=6CmFhMJkIIob7pck -e \"select 1;\""
      interval: 5s
    environment:
      # MySQL isn't publicly visible, there's no real need to be very
      # secure about these passwords
      MYSQL_ROOT_PASSWORD: 6CmFhMJkIIob7pck
      MYSQL_USER: gumbo_usr
      MYSQL_PASSWORD: queedahraes7aifaeshadohs9aiGh1Uh
      MYSQL_DATABASE: gumbo_db
